# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
      - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
      - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
      - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
      - Acme\AuthenticationBundle\Token\CustomAuthenticationToken
    google:
        enabled: true


