#index:
#    path: /
#    controller: src\Controller\HomeController::index


2fa_login:
  path: /2fa
  controller: App\Controller\Front\Security\SecurityController::check2fa

2fa_login_check:
  path: /2fa_check